[build]
builder = "nixpacks"
buildCommand = "yarn install && yarn build"

[deploy]
startCommand = "npx serve -s build -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"