[[services]]
name = "backend"
source = "backend"

[services.build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[services.deploy]
startCommand = "uvicorn server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[services]]
name = "frontend"
source = "frontend"

[services.build]
builder = "nixpacks"
buildCommand = "yarn install && yarn build"

[services.deploy]
startCommand = "npx serve -s build -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"